### ISSUE TITLE
Incorporate additional copy to logo

### ISSUE THREAD

**Issue by jdcauley** [GoodCitizen/CDP-2014#13]
Per Karen: We want to add our tagline "The when, where and how of informed disaster giving" to the logo on the homepage. 

John, what do you think is the best way to handle this?

My initial thought is to incorporate it into the logo png, which how they have it in their current site.

**Comment by johnpeele** [comment]
I moved the wordmark up slightly and added horizontal tagline below while keeping it all centered vertically on the symbol.
